name: "Build nad push to Firebase"

on:
  push:
    branches: ["main"]
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout npm
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Compile contracts
        run: |
          npm ci
          npm run build
        working-directory: contracts
      - name: Build
        run: npm run build
        env:
          REACT_APP_API_URL: "${{ secrets.REACT_APP_API_URL }}"
          REACT_APP_TOKEN_LFT_ADDRESS: "0xD73464667d5F2e15dd0A3C58C3610c39c1b1c2d4"
          REACT_APP_TOKEN_LFN_ADDRESS: "0x0d9D5372b5F889bCEcb930b1540f7D1595075177"
          REACT_APP_TOKEN_NTN_ADDRESS: "0x9019337Ecc929a777B9f87c91D28713496Fc6381"
          REACT_APP_SWAP_CONTRACT_ADDRESS: "0x3896431ca37Cd5D2bE8EaEE7F5F445Ca3A8068B7"
          REACT_APP_STABLE_ADDRESS: "0xb1E34471421DEACda61e68897ED6DBE373169eE9"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./frontend
          firebaseServiceAccount: "${{ secrets.FIREBASE_CREDENTIALS }}"
          projectId: br-hackathon-406413
          channelId: live
