name: "Build nad push to Firebase"

on:
  push:
    branches: ["main"]
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          REACT_APP_API_URL: "${{ secrets.REACT_APP_API_URL }}"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./frontend
          firebaseServiceAccount: "${{ secrets.FIREBASE_CREDENTIALS }}"
          projectId: br-hackathon-406413
          channelId: live
