name: "Build nad push to Firebase"

on:
  push:
    branches: ["main"]
    # paths:
    #   - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Login To GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy
        run: firebase use br-hackathon-406413 && firebase deploy
